# https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/server-types/fabric/
services:
  mc:
    image: itzg/minecraft-server
    container_name: "Fabric"
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "8G"
      TYPE: "FABRIC"
      VERSION: "1.21.4"
      FABRIC_LOADER_VERSION: 0.17.3

    volumes:
      - ./data:/data
