services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    volumes:
    - ./html:/usr/share/nginx/html:ro
    environment:
    - NGINX_HOST=${NGINX_DOMAIN}
    - NGINX_PORT=80
    networks:
      - nginx_caddy

networks:
  nginx_caddy:
    external: true
