# https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/
services:
  luckyblock:
    image: itzg/minecraft-server:java17 # sometimes newer java versions don't work with certain mods
    container_name: "luckyblock"
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "6G"
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-8"

    volumes:
      - ./data:/data
