# https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/#optional-plugins-mods-and-config-attach-points 
services:
  mc:
    image: itzg/minecraft-server
    container_name: "paper"
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "8G"
      TYPE: "PAPER"
      VERSION: "1.21"

    volumes:
      - ./data:/data
      - ./plugins:/data/plugins # copy the plugins (.jar files) here first
