# https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/server-types/forge/
services:
  mc:
    image: itzg/minecraft-server
    container_name: "forge"
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "25567:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "6G"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGE_VERSION: "47.4.0"
      CREATE_CONSOLE_IN_PIPE: "true"
    volumes:
      - ./data:/data
